# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-26 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-similarity_score'],
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=500)),
                ('rss_url', models.CharField(max_length=500, unique=True)),
                ('should_ignore', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('author', models.CharField(default='', max_length=1000)),
                ('summary', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('content', models.TextField(default='')),
                ('raw_description', models.TextField(default='')),
                ('raw_content', models.TextField(default='')),
                ('publication_date', models.DateTimeField()),
                ('url', models.CharField(max_length=1000, unique=True)),
                ('image_url', models.CharField(default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed_fetcher.Feed')),
            ],
            options={
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('base_url', models.CharField(max_length=500, unique=True)),
                ('bias', models.CharField(choices=[('L', 'Left'), ('LC', 'Left-Center'), ('C', 'Center'), ('RC', 'Right-Center'), ('R', 'Right')], max_length=2)),
                ('html_content_tag', models.CharField(default='', max_length=500)),
                ('skip_scraping', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feed_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed_fetcher.FeedItem')),
            ],
        ),
        migrations.AddField(
            model_name='feed',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed_fetcher.Publication'),
        ),
        migrations.AddField(
            model_name='association',
            name='associated_feed_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_associations', to='feed_fetcher.FeedItem'),
        ),
        migrations.AddField(
            model_name='association',
            name='base_feed_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_associations', to='feed_fetcher.FeedItem'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('name', 'feed_item')]),
        ),
    ]
