# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed_fetcher', '0002_auto_20161206_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='feed',
            name='rss_url',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='url',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='base_url',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed_fetcher.FeedItem'),
        ),
    ]
