# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-28 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed_fetcher', '0002_auto_20170226_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpusWordFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=500, unique=True)),
                ('corpus_frequency', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FeedItemWordFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=500)),
                ('feed_item_frequency', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='feeditem',
            name='self_score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feeditemwordfrequency',
            name='feed_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed_fetcher.FeedItem'),
        ),
        migrations.AlterUniqueTogether(
            name='feeditemwordfrequency',
            unique_together=set([('word', 'feed_item')]),
        ),
    ]
