# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 05:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed_fetcher', '0003_auto_20170228_0916'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feeditemwordfrequency',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='feeditemwordfrequency',
            name='feed_item',
        ),
        migrations.RemoveField(
            model_name='corpuswordfrequency',
            name='corpus_frequency',
        ),
        migrations.RemoveField(
            model_name='corpuswordfrequency',
            name='word',
        ),
        migrations.AddField(
            model_name='corpuswordfrequency',
            name='dictionary',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feeditem',
            name='frequency_dictionary',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FeedItemWordFrequency',
        ),
    ]
