# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_fetcher', '0003_auto_20161207_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='feed',
            new_name='feed_item',
        ),
        migrations.AddField(
            model_name='feeditem',
            name='image_url',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
