# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 05:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_fetcher', '0004_auto_20170302_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='frequency_dictionary',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='self_score',
            field=models.FloatField(default=0),
        ),
    ]
