# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_fetcher', '0004_auto_20161207_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='base_url',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
