# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_fetcher', '0005_auto_20161207_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='description',
            field=models.CharField(max_length=50000, null=True),
        ),
    ]
