# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-17 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed_fetcher', '0006_auto_20170303_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapyLogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField()),
                ('content_tag_found', models.BooleanField()),
                ('other_error', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feed_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed_fetcher.FeedItem')),
            ],
        ),
        migrations.AddField(
            model_name='corpuswordfrequency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corpuswordfrequency',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='bias',
            field=models.CharField(choices=[('L', 'Left-Wing'), ('LC', 'Left-Leaning'), ('C', 'Moderate'), ('RC', 'Right-Leaning'), ('R', 'Right-Wing')], max_length=2),
        ),
    ]
