# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_fetcher', '0006_auto_20161207_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='category',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='feed',
            name='rss_url',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='author',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='image_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='url',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='base_url',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
