# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 22:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed_fetcher', '0007_auto_20161207_2152'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('name', 'feed_item')]),
        ),
    ]
