# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-20 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_fetcher', '0008_feeditem_checked_for_associations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeditem',
            name='summary',
        ),
        migrations.AddField(
            model_name='feeditem',
            name='original_url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
