# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed_fetcher', '0008_auto_20161207_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_tag_string', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TopicWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.CharField(max_length=500, unique=True)),
                ('pos_tag', models.CharField(max_length=10)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed_fetcher.Topic')),
            ],
        ),
    ]
