# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_fetcher', '0009_topic_topicword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicword',
            old_name='tag',
            new_name='topic',
        ),
        migrations.RemoveField(
            model_name='topicword',
            name='pos_tag',
        ),
        migrations.AddField(
            model_name='topicword',
            name='pos_type',
            field=models.CharField(choices=[('CD', 'numeral, cardinal'), ('FW', 'foreign word'), ('NAME', "proper noun, organization's name"), ('NAME', "proper noun, person's name"), ('LOC', 'proper noun, location'), ('VERB', 'verb')], default='CD', max_length=5),
            preserve_default=False,
        ),
    ]
