# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-17 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_fetcher', '0010_auto_20170320_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.TextField(default=b''),
        ),
    ]
