# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed_fetcher', '0011_auto_20161211_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associated_feed_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_feed_item', to='feed_fetcher.FeedItem')),
                ('base_feed_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_feed_item', to='feed_fetcher.FeedItem')),
                ('topics', models.ManyToManyField(to='feed_fetcher.Topic')),
            ],
        ),
    ]
