# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-19 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_fetcher', '0011_auto_20170417_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='lookup_url',
            field=models.CharField(default=b'', max_length=1000),
        ),
    ]
