# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-23 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_fetcher', '0012_feeditem_lookup_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='redirected_url',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
