# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed_fetcher', '0012_association'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeditem',
            options={'ordering': ['-publication_date']},
        ),
        migrations.AddField(
            model_name='feed',
            name='should_ignore',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='association',
            name='associated_feed_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_associations', to='feed_fetcher.FeedItem'),
        ),
        migrations.AlterField(
            model_name='association',
            name='base_feed_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_associations', to='feed_fetcher.FeedItem'),
        ),
    ]
