# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-24 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_fetcher', '0013_auto_20170423_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='lookup_url',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
