# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 01:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed_fetcher', '0013_auto_20170107_2326'),
    ]

    operations = [
      migrations.RenameField('FeedItem', 'description', 'raw_description')
    ]
