# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_fetcher', '0014_auto_20170108_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='feeditem',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='feeditem',
            name='raw_content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='feeditem',
            name='summary',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
