# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-05 09:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed_fetcher', '0014_auto_20170424_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLLookUpRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('code', models.CharField(choices=[('1', 'Found with lookup URL'), ('2', 'Found with redirect URL'), ('3', 'Found with normal URL'), ('N/A', 'Not found'), ('Base', 'Base URL')], max_length=10)),
                ('associations_found', models.IntegerField(default=0)),
                ('internal_user', models.BooleanField()),
                ('feed_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed_fetcher.FeedItem')),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_negative', models.BooleanField()),
                ('feedback_version', models.IntegerField()),
                ('feedback_dict', django.contrib.postgres.fields.jsonb.JSONField()),
                ('other_feedback', models.TextField(default='')),
                ('free_text_feedback', models.TextField(default='')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed_fetcher.Association')),
            ],
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
