# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-05 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed_fetcher', '0015_auto_20170505_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urllookuprecord',
            name='associations_found',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='urllookuprecord',
            name='feed_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feed_fetcher.FeedItem'),
        ),
        migrations.AlterField(
            model_name='urllookuprecord',
            name='internal_user',
            field=models.BooleanField(default=False),
        ),
    ]
