# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-13 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed_fetcher', '0016_auto_20170505_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed_fetcher.Association')),
            ],
        ),
        migrations.AddField(
            model_name='urllookuprecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urllookuprecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='internal_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
