# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_fetcher', '0017_auto_20170109_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='author',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='image_url',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='url',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
