# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-26 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_fetcher', '0017_auto_20170513_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeedback',
            name='free_text_feedback',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='other_feedback',
        ),
        migrations.AddField(
            model_name='userclick',
            name='internal_user',
            field=models.BooleanField(default=False),
        ),
    ]
