# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_fetcher', '0018_auto_20170109_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='html_content_tag',
            field=models.CharField(default='', max_length=500),
        ),
    ]
