# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-26 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed_fetcher', '0018_auto_20170526_0709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfeedback',
            old_name='internal_user',
            new_name='is_internal_user',
        ),
        migrations.RemoveField(
            model_name='urllookuprecord',
            name='internal_user',
        ),
        migrations.RemoveField(
            model_name='userclick',
            name='internal_user',
        ),
    ]
