# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-05 12:50
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed_fetcher', '0019_auto_20170526_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpectrumUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_internal_user', models.BooleanField(default=False)),
                ('unique_id', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='is_internal_user',
        ),
        migrations.AddField(
            model_name='userclick',
            name='clicked_item_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='userclick',
            name='clicked_version',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='feed_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feed_fetcher.FeedItem'),
        ),
        migrations.AlterField(
            model_name='userclick',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feed_fetcher.Association'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feed_fetcher.Association'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='feedback_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='urllookuprecord',
            name='spectrum_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feed_fetcher.SpectrumUser'),
        ),
        migrations.AddField(
            model_name='userclick',
            name='spectrum_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feed_fetcher.SpectrumUser'),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='spectrum_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feed_fetcher.SpectrumUser'),
        ),
    ]
