# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-25 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed_fetcher', '0020_auto_20170225_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeditem',
            name='content_missing',
        ),
    ]
