# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-05 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed_fetcher', '0020_auto_20170605_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spectrumuser',
            name='is_internal_user',
        ),
    ]
