# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-05 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_fetcher', '0021_remove_spectrumuser_is_internal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclick',
            name='element_selector',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='spectrumuser',
            name='unique_id',
            field=models.TextField(default='', unique=True),
        ),
    ]
