# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-25 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_fetcher', '0022_auto_20170225_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='similarity_score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
