# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-06 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_fetcher', '0022_auto_20170605_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='feedback_version',
            field=models.FloatField(default=0.2),
        ),
    ]
