# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('rss_url', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('publication_date', models.DateField()),
                ('url', models.CharField(max_length=300)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed_fetcher.Feed')),
            ],
            options={
                'ordering': ['publication_date'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_url', models.CharField(max_length=100)),
                ('bias', models.CharField(choices=[('L', 'Left'), ('LC', 'Left-Center'), ('C', 'Center'), ('RC', 'Right-Center'), ('R', 'Right')], max_length=2)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='feed',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed_fetcher.Publication'),
        ),
    ]
